### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by sahdev0** [Luehang/react-native-masonry-list#1]
Hello @Luehang 

I am trying to add your library for masonry layout in my project. After install and import Component getting an error - module cannot found.

Can you please fix this issue.

I am using 
RN : 0.57
Gradle: 4.x

**Comment by Luehang** [comment]
Hi sahdev0,

I will be happy to help you out.

This probably isn't a `react-native-masonry-list` problem.  If you are missing the module, I think you should **reinstall** the module again.  Type in the following onto the command line.  

```bash
$ npm install --save react-native-masonry-list@1.2.7
```

If you are **still** getting problems, how did you `import` the module?  The following codes are examples of importing modules.  The first one is the latest syntax and the other one is the old one which will still work.

```javascript
import MasonryList from "react-native-masonry-list";
```
**OR**
```javascript
const MasonryList = require("react-native-masonry-list");
```

If the above did not fix the issue, did you go into your `node_modules` directory and check if you have the  `react-native-masonry-list` directory.  Make sure it exists in the `node_modules` directory.

```bash
**YourProjectName**/node_modules/react-native-masonry-list
```

And **make sure** there are files in the `react-native-masonry-list` directory.

If these solutions did not solve the error, then can you snapshot the error?

Thanks.

**Comment by Luehang** [comment]
If you would like to learn more about **React Native development**, visit this site.  https://luehangs.site/blogs/react-native-development .  I will be happy to help you out.

**Comment by sahdev0** [comment]
Hello @Luehang 

I followed all the steps you have provided but still cannot import this module. TO find the I dug down to your plugin, which I want to share with you

1) In the first step when I installed this plugin and import into my code but failed to locate and followed your plugin root found exports like this:

**import MasonryList from "./src";
module.exports = MasonryList;**

2) In 2nd step, I changed to this

**import MasonryList from "./src";
export default MasonryList;**

Now I can locate your module, If you find this approach is incorrect, please guide me for the correct module export method.


Note: onImagePress() function also not working, for that, I have downloaded your code and made some changes now it's working as I expected if you don't mind I want to share with you

**Comment by Luehang** [comment]
Hi sahdev0,

Thanks for pointing that out.  I appreciate it.

The `module.exports` I had is old syntax.  I will replace it with the new one.  If you would like to be a contributor, can you do a pull request?

As for the **press** function, it is called `onPressImage() => void` not `onImagePress()`.

Thanks for filing an issue.  It means a lot, and helps me improve the package.

**Comment by Luehang** [comment]
And if you would like to install the latest version by typing in `npm install --save react-native-masony-list@latest`.  I just recently improved and fix bugs for this package again.
