### ISSUE TITLE
Is it Possible for CardView? 

### ISSUE THREAD

**Issue by EdisonDevadoss** [Luehang/react-native-masonry-list#10]

**Comment by Luehang** [comment]
Hi,

Can you elaborate on what you mean?

**Comment by EdisonDevadoss** [comment]
Can it possible show inside the native base card view.

**Comment by Luehang** [comment]
There are work arounds for this.  You can use the prop `completeCustomComponent` with the following params, `({ source: object, style: { width: number, height: number, margin: number }, data: object }) => React.Element`.  This function is called to render each image. This function must return a React Component and it is required to have the source and style for the component to display proper masonry.

**Comment by Luehang** [comment]
Go to this link, if you want to download a [free mobile starter kit](https://luehangs.site/marketplace/product/RN%20Posting%20Demo%20App%20Kit) that shows how to build a high quality app.
