### ISSUE TITLE
borderRadious to image cell

### ISSUE THREAD

**Issue by dhanababum** [Luehang/react-native-masonry-list#13]
Hi I am trying to apply BorderRadious, But it still showing corner edges,

imageContainerStyle={{
				borderRadius: 10,
				borderWidth: 1,
				borderColor: '#fff',
				overflow: 'hidden'
			}}

![2019-03-11](https://user-images.githubusercontent.com/5729855/54146806-cab13c80-4456-11e9-9398-40e83fe7d4ff.jpg)

**Comment by Luehang** [comment]
Hi,

What version are you using?  And can I see the full code?  I tried reproducing the same issue, but did not see that.

**Comment by dhanababum** [comment]
Here is full code,

```
<MasonryList
			// sorted // optional - Default: false
			// columns={4} // optional - Default: 2
			imageContainerStyle={{
				borderRadius: 18,
				borderWidth: 4,
				borderColor: '#fff',
				overflow: 'hidden'
			}}
			initialNumInColsToRender={2}
			onPressImage={(item) => navigation.navigate('Detail', { row: item })}
			images={items.map((item) => ({ uri: item.image.downloadURL }))}
		/>
```

Package Version:

```
"react-native-masonry-list": "^2.8.1"
"react-native": "0.52.0"
```

**Comment by Luehang** [comment]
Hi,

I think it's a React Native border radius bug on iOS.  A temporary fix is to add `backgroundColor: "white"` in the `imageContainerStyle` prop **or** upgrade to `react-native` to the latest version.

**Comment by dhanababum** [comment]
Thanks for reply, But I was using Android.

**Comment by Luehang** [comment]
On iOS, there are known to be issues with the `borderRadius`.  If it's on Android, a temporary fix is to add `backgroundColor: "white"` in the `imageContainerStyle` prop **or** upgrade to `react-native` to the latest version.  I am on `react-native` version **0.58.4** and I don't see any visible bugs.

**Comment by Luehang** [comment]
Another alternative is to fully customize the image component of the `react-native-masonry-list`.  The description is shown below on how to use it.  If you would like an example, let me know.  I would be happy to help you out.

<br/>

# :large_blue_diamond: Props
| Props                         | Description                                                                                                                                                                                    | Type              | Default |
|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------|---------|
| `completeCustomComponent`     | Custom function to return a fully custom component for each image.  `({ source: object, style: { width: number, height: number, margin: number }, data: object }) => React.Element`  This function must return a React Component and it is required to have the source and style for the component to display proper masonry. | `Function` | |
