### ISSUE TITLE
Masnory list props not updated while I am change footer text.

### ISSUE THREAD

**Issue by EdisonDevadoss** [Luehang/react-native-masonry-list#16]
In my masnory-list I have shown an image with some text. I have the option to edit the texts. After I finished my editing my props are changed but it's not changed in masnory-list.

Help me.

**Comment by Luehang** [comment]
Hi,

I tried reproducing the same results and the function props seems to be rendering the props and state just like it is suppose to.  Can I see your code that you are using?

**Comment by Luehang** [comment]
:+1: If you like [`react-native-masonry-list`](https://github.com/Luehang/react-native-masonry-list), please be sure to give it a star. Thanks.

**Comment by kimjoongwon** [comment]
same issue -_-; footer...TT
