### ISSUE TITLE
keeps re-rendering when using state data

### ISSUE THREAD

**Issue by lashansam** [Luehang/react-native-masonry-list#17]
When I use state data(ex. this.state.data) to render the list, it keeps refreshing when I add more data. Any solution for this?

**Comment by mailaustin37** [comment]
Experiencing this also on Android.
"react": "16.6.3",
"react-native": "0.57.4",
"react-native-masonry-list": "^2.10.0"

**Comment by Tatvanish** [comment]
+1

**Comment by NguyenVanVietPoLy** [comment]
any one can fix that bug?

**Comment by bluedevstorm** [comment]
+1

**Comment by FauricioValencia** [comment]
+1

**Comment by hejun041** [comment]
[https://github.com/hejun041/react-native-masonry-list/blob/master/HowToUse.md](url)
can solve sort bug and add extra data
hope help

**Comment by Luehang** [comment]
Hi everyone,

New stable update will be coming out soon.  In a couple of days.  @hejun041, those are some good fixes.  You will be added to the contribution section, but next time, can you do a clean pull request?

**Comment by Luehang** [comment]
## Install the update

Type in the following to install the update.

```bash
$ npm install --save react-native-masonry-list@2.12.0
```

or

```bash
$ yarn add react-native-masonry-list@2.12.0
```

**Comment by Luehang** [comment]
## :tada: Efficiently Add More Images

**Version \*2.12.0 update:** Without rerendering the images.

```javascript
import MasonryList from "react-native-masonry-list";

//...
// example function to add more images
addMoreImages(newImages) {
    this.setState({
        images: this.state.images.concat(newImages)
    });
}

render() {
    return (
        <MasonryList
            images={this.state.images}
        />
    );
}
//...
```

:+1: If you like [`react-native-masonry-list`](https://github.com/Luehang/react-native-masonry-list), please be sure to give it a star. Thanks.
