### ISSUE TITLE
ListHeaderComponent question

### ISSUE THREAD

**Issue by lmh87883819** [Luehang/react-native-masonry-list#19]
when i use ListHeaderComponent ,it doesnt wrok

**Comment by Luehang** [comment]
Hi,

The `FlatList` is used differently in `react-native-masonry-list`.  If you checkout the example project, there is another way to have the header on top of the masonry.

**Comment by lmh87883819** [comment]
but i need it scroll with list😢

**Comment by hejun041** [comment]
Same here
When I use ListHeaderComponent ,header works,but List not render

**Comment by hejun041** [comment]
hey,it works
when you use ListHeaderComponent ,you need change spacing value to 0
and set FlatList's contentContainerStyle like this:
 `contentContainerStyle={{
                            flexWrap: 'wrap',
                            flexDirection: "row",
                        }}`
and change your completeCustomComponent's style
