### ISSUE TITLE
onEndReached re render all images every time

### ISSUE THREAD

**Issue by EnanlyPay** [Luehang/react-native-masonry-list#20]
Thank you for the library. Everything seems to be working fine except when onEndReached is called, all images are re rendered. Is there a way to fix this issue ?

**Comment by hejun041** [comment]
[https://github.com/hejun041/react-native-masonry-list](url)
may help

**Comment by EnanlyPay** [comment]
Thanks closing

**Comment by jasminmesada** [comment]
Hi how did you fix onEndReached call all images?

**Comment by Luehang** [comment]
## :tada: Efficiently Add More Images

**Version \*2.12.0 update:** Without rerendering the images.

```javascript
import MasonryList from "react-native-masonry-list";

//...
// example function to add more images
addMoreImages(newImages) {
    this.setState({
        images: this.state.images.concat(newImages)
    });
}

render() {
    return (
        <MasonryList
            images={this.state.images}
        />
    );
}
//...
```

:+1: If you like [`react-native-masonry-list`](https://github.com/Luehang/react-native-masonry-list), please be sure to give it a star. Thanks.
