### ISSUE TITLE
example project build failed

### ISSUE THREAD

**Issue by Frekansapp** [Luehang/react-native-masonry-list#21]
this is output after enter terminal to react-native run-android command [maybe relevant](https://github.com/gradle/gradle/issues/8436)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:629:11)
    at Object.execFileSync (child_process.js:647:13)
    at runOnAllDevices (/home/rn/Desktop/react-native-masonry-list-master/example/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/home/rn/Desktop/react-native-masonry-list-master/example/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/home/rn/Desktop/react-native-masonry-list-master/example/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Frekansapp** [comment]
@Luehang this libs have performance issue too. I managed to run. After scroll few times the screen darkens and the application crashes.

**Comment by Luehang** [comment]
Hi @Frekansapp,

`react-native-masonry-list` is constantly being updated and the example project just hasn't been updating with it constantly.  To temporarily fix this problem, use the following codes in your project. 


## :tada: Usage Example

> If you like [`react-native-masonry-list`](https://github.com/Luehang/react-native-masonry-list), please be sure to give it a star. Thanks and have a good day!

```javascript
import MasonryList from "react-native-masonry-list";

//...
render() {
    return (
        <MasonryList
            images={[
                // Can be used with different image object fieldnames.
                // Ex. source, source.uri, uri, URI, url, URL
                { uri: "https://luehangs.site/pic-chat-app-images/beautiful-blond-blonde-hair-478544.jpg" },
                { source: { uri: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-women-beauty-40901.jpg" } },
                { uri: "https://luehangs.site/pic-chat-app-images/animals-avian-beach-760984.jpg",
                    // Optional: Adding a dimensions field with
                    // the actual width and height for REMOTE IMAGES
                    // will help improve performance.
                    dimensions: { width: 1080, height: 1920 } },
                { URI: "https://luehangs.site/pic-chat-app-images/beautiful-blond-fishnet-stockings-48134.jpg",
                    // Optional: Does not require an id for each
                    // image object, but is for best practices.
                    id: "blpccx4cn" },
                { url: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-woman-beauty-9763.jpg" },
                { URL: "https://luehangs.site/pic-chat-app-images/attractive-balance-beautiful-186263.jpg" },
            ]}
        />
    );
}
//...
```

<br/>

The example project will be looked at soon and will be fix and updated.

**Comment by Luehang** [comment]
If you're looking for a high quality app that shows you how to use Redux, Redux Saga, Select and React Navigation plus a whole lot more helpful things, go to https://luehangs.site/marketplace/product/RN%20Posting%20Demo%20App%20Kit.

**Comment by Frekansapp** [comment]
Delete other codes and render just MasonryList solved the performance issue. Thank you

**Comment by Luehang** [comment]
:+1: If you like [`react-native-masonry-list`](https://github.com/Luehang/react-native-masonry-list), please be sure to give it a star. Thanks.
