### ISSUE TITLE
sorting not working properly

### ISSUE THREAD

**Issue by hardlife11** [Luehang/react-native-masonry-list#23]
hi ,
thanks for the library. i am facing problem with sorted, on few first load the order is messed but after that the order is perfect based on index.

**Comment by Luehang** [comment]
Hi,

Can you provide your code that you use and which platform along with anything else that is useful?

**Comment by hardlife11** [comment]
Environment
Platform: iOS and Android
react-native: 59 with expo-sdk 33
react-native-masonry-list: ^2.10.4

function to get data
`photos.map(data => {
            let pic = {
              id: data.id,
              uri: data.photo
            }
            this.userPhotos = this.userPhotos.concat(pic)
`
then I replace data to state
`this.setState({
      photoCollection: this.state.photoCollection.concat(toJS(this.props.userStore.userPhotos))
    })
`

And here the Masonry 
`<MasonryList
            sorted = {true}
            images={this.state.photoCollection}
            onPressImage={(photo) => this.props.navigation.navigate("/user/photo-detail", { id:photo.id , onGoBack: () => this.refresh() })}
          />
`

**Comment by Luehang** [comment]
Can you update the package and see if it solve it?

Type in the following to the command line to update.

```bash
$ npm install --save react-native-masonry-list@latest
```

or

```bash
$ yarn add react-native-masonry-list@latest
```

**Comment by hardlife11** [comment]
it fixes my issues , thanks for the help and reply

**Comment by Luehang** [comment]
:+1: If you like [`react-native-masonry-list`](https://github.com/Luehang/react-native-masonry-list), please be sure to give it a star. Thanks.
