### ISSUE TITLE
Unable to implemented pagination. FlatList not rerendered on updating data in image array.

### ISSUE THREAD

**Issue by abhay2152** [Luehang/react-native-masonry-list#24]

**Comment by Luehang** [comment]
Hi,

Can you provide your code that you use and which platform along with anything else that is useful?

**Comment by abhay2152** [comment]
@Luehang , I am using 2.2.7 version of react-native-masonry-list. Using on both iOS and android


<MasonryList
                    sorted
                    columns={2}
                    spacing={1}
                    count={count}
                    initialNumInColsToRender={5}
                    completeCustomComponent={this.renderCellComponent}
                    masonryFlatListColProps={masonryFlatListColProps}
                    images={this.getImageUrlListing()}
                />


and passing onEndReached and handlePullToRefresh function in masonryFlatListColProps, and this component is rerendered when data in images array updated. When i debug the library internaly,

the following function written in componentWillRecieveProps(),

this.resolveImages(
				nextProps.itemSource,
				nextProps.images,
				nextProps.layoutDimensions,
				nextProps.columns,
				nextProps.initialColToRender,
				nextProps.initialNumInColsToRender,
				nextProps.sorted
			);

is not executed again and thats why data in list in not updated. Urgent Help needed. Please Suggest.

**Comment by Luehang** [comment]
Hi,

Can you update the package to latest?

## Install

Type in the following to the command line.

```bash
$ npm install --save react-native-masonry-list@latest
```

or

```bash
$ yarn add react-native-masonry-list@latest
```

`onEndReached` is not entirely supported at the moment, but will be in the future.

<br/>

***
<br/>

## :tada: Efficiently Add More Images

**Version \*2.12.0 update:** Without rerendering the images.

```javascript
import MasonryList from "react-native-masonry-list";

//...
/**
 * Example method to add more images.
 *
 * @method addMoreImages
 */
addMoreImages(newImages) {
    this.setState({
        images: this.state.images.concat(newImages)
    });
}

render() {
    return (
        <MasonryList
            images={this.state.images}
        />
    );
}
//...
```

<br/>

***
<br/>

## :tada: Add New Images

**Version \*2.13.0 update:** Rerendering the images.

```javascript
import MasonryList from "react-native-masonry-list";

//...
/**
 * Example method to add new images.
 *
 * @method addNewImages
 * @config Set react-native-masonry-list's "rerender" prop to true.
 */
addNewImages(newImages) {
    this.setState({
        images: newImages
    });
}

render() {
    return (
        <MasonryList
            rerender={true}
            images={this.state.images}
        />
    );
}
//...
```

**Comment by Luehang** [comment]
If you like [`react-native-masonry-list`](https://github.com/Luehang/react-native-masonry-list), please be sure to give it a star.
