### ISSUE TITLE
how to give onpress props on image tap

### ISSUE THREAD

**Issue by stepupithubapp** [Luehang/react-native-masonry-list#35]
**To Do First**
<MasonryList
            rerender = {true}
            images = {photoGroup[albumname]}
            onPressImage = {({item, index}) => this._openImage}
            columns={3}
            />
# Lue Hang

**Comment by stepupithubapp** [comment]
plz anybody can help me

**Comment by Luehang** [comment]
Hi, you can use the `completeCustomComponent`.

| Props                         | Description                                                                                                                                                                                    | Type              | Default |
|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------|---------|
| `customImageComponent`        | Use a custom component to be rendered for the image as long as the component follows the standard interface of the `react-native` `Image` component. **Version \*1.2.2 update**. | `React.Component` | `Image` module import of react-native |

Take a look at the [`react-native-camera-roll-selector`](https://github.com/Luehang/react-native-camera-roll-selector).

**Comment by jpouabou** [comment]
Can you give an example of completeCustomComponent @Luehang ?
Thanks.
