### ISSUE TITLE
not rerendering when data changes[BUG]

### ISSUE THREAD

**Issue by stepupithubapp** [Luehang/react-native-masonry-list#36]
**To Do First**
- [ ] Did you try latest release?
- [ ] Did you look for existing matching issues?

**Software Package Version:**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Android:
 - iOS:
 - react-native:
 - react:

**Additional context**

**Comment by Luehang** [comment]
Hi,

This issue will be reopen when you fill out the entire form and give more info.  And your code you use.

**Comment by stepupithubapp** [comment]
hellooo #Luehang

**Comment by stepupithubapp** [comment]
@Luehang  
 <MasonryList
           rerender={true}
              images={this.state.data}
               extraData={this.state}
               keyExtractor = { (item, index) => index + ''}
               onPressImage={({item, index}) => this._openImage(item, index)}
           onLongPressImage = {(item, index) => this._openImage(item, index)}
           columns={3}
              />

**Comment by stepupithubapp** [comment]
as per define in above example i'm data from state but when my state changes i mean when i initialise the data its like 10 items but after changes i get 9 items but in this library its not rendering changed data
