### ISSUE TITLE
Optional overlay

### ISSUE THREAD

**Issue by drplauska** [Luehang/react-native-masonry-list#38]
Is there a possibility to add an overlay, such as transparent grey colour, and make an onpress prop disabled for some items? 
such as adding:
```
{
  id: 3,
  disabled: true,
  uri:  'https://vignette.wikia.nocookie.net/learn-your-meme/images/5/5c/Longcat.jpg/revision/latest?cb=20150517184158',
},
```
would do the job

**Comment by Luehang** [comment]
Hi, you can use the `completeCustomComponent`.

| Props                         | Description                                                                                                                                                                                    | Type              | Default |
|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------|---------|
| `completeCustomComponent`     | This Function or React Component is called as an alternative to render each image. Must return a React Element or Component, and it is required to have the source and style for the component to display proper masonry. `({ source: object, style: { width: number, height: number, margin: number }, data: object }) => React.Element` **Version \*1.2.2 update**. | `Function` or `React.Component` | |
