### ISSUE TITLE
[QUESTION] How to implement ListHeaderComponent on Top of list, not side to side with list

### ISSUE THREAD

**Issue by risardi123** [Luehang/react-native-masonry-list#48]
**Ask your Question**
Hi luehang, first I want to say thank you  to make this library.

I have an issue with header component, when I want to use header component, I used this masonryFlatListColProps and success, but the layout seems not correct for me. see image for more.

calling props 

> masonryFlatListColProps={
            {
              ListHeaderComponent:()=>{
                return(
                  <Text style={{backgroundColor: 'lightgreen'}}>
                    This is header Component
                  </Text>
                )
              }
}}
as I expect like the right screen.
<img width="1174" alt="Screen Shot 2020-02-14 at 11 15 17" src="https://user-images.githubusercontent.com/29408156/74501004-5828c680-4f1b-11ea-914d-f9e04baa3f62.png">

Thank you

Notes: I was try wrap the `<Masonry/>` with `<ScrollView/>` but I think it's not the best way to implement it. I think it will impact with the perfomance and onEndReached flatlist cannot be triggered inside scrollView component.

**Tags**
@Luehang @sahdev0

**Comment by CallMeHeisenberg** [comment]
Hey, I'm using the library for my project and the solution that I came up with was
`listContainerStyle={{justifyContent: "center", flexWrap: 'wrap', flexDirection: "row"}}`

Hope it helps ))

**Comment by risardi123** [comment]
@came

> Hey, I'm using the library for my project and the solution that I came up with was
> `listContainerStyle={{justifyContent: "center", flexWrap: 'wrap', flexDirection: "row"}}`
> 
> Hope it helps ))
> 
> PS: Add this line to your MansoryList and get rid of the outer Scroll

Thanks bro, I will try it 👍👍

**Comment by risardi123** [comment]
> Hey, I'm using the library for my project and the solution that I came up with was
> `listContainerStyle={{justifyContent: "center", flexWrap: 'wrap', flexDirection: "row"}}`
> 
> Hope it helps ))
> 
> PS: Add this line to your MansoryList and get rid of the outer Scroll

Thank you it's working like a charm. and don't forget to add `columns` and set width for your header.
