### ISSUE TITLE
How to add image dynamically from server

### ISSUE THREAD

**Issue by amarhunter** [Luehang/react-native-masonry-list#8]
I am new to react native. I don't know how to add image dynamically in page

**Comment by Luehang** [comment]
Hi,

When you fetch an image or images, `setState()` for the images fetched.  Before you do that, return a `react-native-masonry-list` component to the `render()` function and place the **state** array of images to the `images` prop.

## :large_blue_diamond: Example

```javascript
import React, { Component } from "react";
import MasonryList from "react-native-masonry-list";

class Example extends Component {
	state = {
  	        images: []
        }
  
	componentDidMount() {
  	       fetch('https://api.example.com/server/endpoint')
                        .then((response) => response.json())
                        .then((data) => {
                                 this.setState({
        	                          images: data
                                 });
                        });
        }
  
	render() {
  	       return (
    	               <MasonryList
      	                        images={this.state.images}
                       />
               );
        }
}
```

**Comment by Luehang** [comment]
Be sure to give a `react-native-masonry-list` a star, if you liked it.  And download a [free mobile starter kit](https://luehangs.site/marketplace/product/RN%20Posting%20Demo%20App%20Kit) that shows how to build a high quality app.
