### ISSUE TITLE
Usage Without Images?

### ISSUE THREAD

**Issue by Slapbox** [Luehang/react-native-masonry-list#9]
This looks really excellent! Is it possible to use this without images and to render `<View />` tags instead?

**Comment by Luehang** [comment]
Hi,

I think right now it will display an empty flatlist, but you can use an **if statement** to render a `<View />` tag.  If you like this `react-native-masonry-list`, be sure to give it a star!  Thanks!

<br/>

## :large_blue_diamond: Custom Example

```javascript
\\ ...
const thereIsNoImages = this.state.imagesData.length === 0;
if (thereIsNoImages) {
    return <View />;
}
\\ ...
```

In future releases, there will be a `customEmptyComponent` prop.

<br/>

**Comment by Luehang** [comment]
Go to this link, if you want to download a [free mobile starter kit](https://luehangs.site/marketplace/product/RN%20Posting%20Demo%20App%20Kit) that shows how to build a high quality app.

**Comment by Toothless1118** [comment]
@Luehang 
Very useful and amazing package.
Could you please let me know where should I add this if statement?

const thereIsNoImages = this.state.imagesData.length === 0;
if (thereIsNoImages) {
    return <View />;
}

Thanks

**Comment by Luehang** [comment]
Hi,

Here is an example.

<br/>

## :large_blue_diamond: Example

```javascript
import React, { Component } from "react";
import { View } from "react-native";
import MasonryList from "react-native-masonry-list";

class Example extends Component {
  state = {
    images: []
  }
  
  componentDidMount() {
    fetch('https://api.example.com/server/endpoint')
      .then((response) => response.json())
      .then((data) => {
        this.setState({
        	images: data
        });
      });
  }

  render() {
    const thereIsNoImages = this.state.images.length === 0;
    if (thereIsNoImages) {
    	return <View />;
    }
    return (
      <MasonryList
      	images={this.state.images}
      />
    );
  }
}
```

<br/>

Give this `react-native-masonry-list` a star if you liked it!  Thanks.

**Comment by Luehang** [comment]
New update includes an `emptyView` prop.

<br/>

## :large_blue_diamond: Install

Type in the following to the command line to install the latest.

```bash
$ npm install --save react-native-masonry-list@latest
```

or

```bash
$ yarn add react-native-masonry-list@latest
```

<br/>

# :large_blue_diamond: Props

<br/>

| Props                         | Description                                                                                                                                                                                    | Type              | Default |
|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------|---------|
| `emptyView`                   | A component, React Element, or function that is executed when there is no images. | `React.Element` or `Function` | undefined |
